# import models

In [1]:
import ete3
from ete3 import Tree
import numpy as np
import pandas as pd
import string
from random import choice, choices
import os
from pathlib import Path

In [2]:
import os
import math
import numpy as np
import pandas as pd

from ete3 import Tree
from joblib import Parallel, delayed

def get_dist_to_ancestor(tree, ancestor_node, target_node):
    dist = 0
    current = target_node
    while True:
        if current == ancestor_node:
            dist += 1
            break
        if current.up is None:
            # 已到根仍未找到
            break
        current = current.up
        dist += 1
    return dist

def compute_subtree_depth_info(tree):
    nodes = [i for i in tree.traverse() if not i.is_leaf()]
    ## Dr (distance to root)
    ## Ds (distance to farthest leaf)
    # mdepth = ((Dr/Dt) + (1 - Ds/Dt))/2 
    # node.height = 1 - mdepth
    Dr_vals = {}
    Ds_vals = {}
    for node in nodes:
        # for Dr calculate
        up_dist = 0
        tmp_up = node
        while tmp_up.up is not None:
            tmp_up = tmp_up.up
            up_dist += 1
        Dr_vals[node.name] = float(up_dist)
        # for Ds calculate
        farthest_leaf = node.get_farthest_leaf()
        down_dist = 0
        tmp_down = farthest_leaf[0]
        while tmp_down != node and tmp_down is not None:
            tmp_down = tmp_down.up
            down_dist += 1
        Ds_vals[node.name] = float(down_dist)


    # Dt (max Ds)
    Dt = max(Ds_vals.values())
    # calculate node.height
    #  mdepth = ((Dr/Dt) + (1 - Ds/Dt))/2 
    #  node.height = 1 - mdepth
    node_depth = {}
    node_height = {}
    for re_node in nodes:
        Dr = Dr_vals[re_node.name]
        Ds = Ds_vals[re_node.name]
        node_depth[re_node.name] =  Ds / Dt
        mdepth = ((Dr / Dt) + (1 - Ds / Dt)) / 2
        node_height[re_node.name] = 1 - mdepth
        

    # dict
    subtree_depth = {
        'Dr': Dr_vals,
        'Ds': Ds_vals,
        'depth': node_depth,
        'height': node_height,
        'max_ds': Dt,
    }
    return subtree_depth

# generate the two phase transition matrix

In [3]:
phase_1_transmx = pd.read_csv("/mnt/data5/disk/yangwj/Scripts/Fig2/new_two_phase_tree/phase_1_transmatrix.txt", sep='\t', index_col=0)
phase_2_transmx = pd.read_csv("/mnt/data5/disk/yangwj/Scripts/Fig2/new_two_phase_tree/phase_2_transmatrix_2.txt", sep='\t', index_col=0)

In [4]:
phase_1_transmx

      A     B     C     D
A  0.64  0.12  0.12  0.12
B  0.12  0.64  0.12  0.12
C  0.12  0.12  0.64  0.12
D  0.12  0.12  0.12  0.64

In [5]:
phase_2_transmx

   A  B    C    D     E     F     G     H
A  1  0  0.0  0.0  0.00  0.00  0.00  0.00
B  0  1  0.0  0.0  0.00  0.00  0.00  0.00
C  0  0  0.7  0.1  0.10  0.10  0.00  0.00
D  0  0  0.1  0.7  0.10  0.10  0.00  0.00
E  0  0  0.0  0.0  0.64  0.12  0.12  0.12
F  0  0  0.0  0.0  0.12  0.64  0.12  0.12
G  0  0  0.0  0.0  0.12  0.12  0.64  0.12
H  0  0  0.0  0.0  0.12  0.12  0.12  0.64

# new generation of tree

In [6]:
phase_tree_bb = Tree("/mnt/data5/disk/yangwj/Scripts/Fig2/new_two_phase_tree/new_two_phase_tree_50000_format1.nwk", format=1)

In [7]:
phase_tree_2 = phase_tree_bb.copy()

In [8]:
# 2. name each node and cite depth and mheight in each node
i = 1
for each_node in phase_tree_2.traverse():
    each_node.name = "N_" + str(i)
    each_node.dist = 1
    i += 1

In [9]:
subtree_depth_infos_2 = compute_subtree_depth_info(phase_tree_2)

In [10]:
subtree_depth_infos_2

{'Dr': {'N_1': 0.0,
  'N_2': 1.0,
  'N_3': 1.0,
  'N_4': 2.0,
  'N_5': 2.0,
  'N_6': 2.0,
  'N_7': 2.0,
  'N_8': 3.0,
  'N_9': 3.0,
  'N_10': 3.0,
  'N_11': 3.0,
  'N_12': 3.0,
  'N_13': 3.0,
  'N_14': 3.0,
  'N_15': 3.0,
  'N_16': 4.0,
  'N_17': 4.0,
  'N_18': 4.0,
  'N_19': 4.0,
  'N_20': 4.0,
  'N_21': 4.0,
  'N_22': 4.0,
  'N_23': 4.0,
  'N_24': 4.0,
  'N_25': 4.0,
  'N_26': 4.0,
  'N_27': 4.0,
  'N_28': 4.0,
  'N_29': 4.0,
  'N_30': 4.0,
  'N_31': 4.0,
  'N_32': 5.0,
  'N_33': 5.0,
  'N_34': 5.0,
  'N_35': 5.0,
  'N_36': 5.0,
  'N_37': 5.0,
  'N_38': 5.0,
  'N_39': 5.0,
  'N_40': 5.0,
  'N_41': 5.0,
  'N_42': 5.0,
  'N_43': 5.0,
  'N_44': 5.0,
  'N_45': 5.0,
  'N_46': 5.0,
  'N_47': 5.0,
  'N_48': 5.0,
  'N_49': 5.0,
  'N_50': 5.0,
  'N_51': 5.0,
  'N_52': 5.0,
  'N_53': 5.0,
  'N_54': 5.0,
  'N_55': 5.0,
  'N_56': 5.0,
  'N_57': 5.0,
  'N_58': 5.0,
  'N_59': 5.0,
  'N_60': 5.0,
  'N_61': 5.0,
  'N_62': 5.0,
  'N_63': 5.0,
  'N_64': 6.0,
  'N_65': 6.0,
  'N_66': 6.0,
  'N_67': 6.0,
  'N_68': 6.0,
  'N_69': 6.0,
  'N_70': 6.0,
  'N_71': 6.0,
  'N_72': 6.0,
  'N_73': 6.0,
  'N_74': 6.0,
  'N_75': 6.0,
  'N_76': 6.0,
  'N_77': 6.0,
  'N_78': 6.0,
  'N_79': 6.0,
  'N_80': 6.0,
  'N_81': 6.0,
  'N_82': 6.0,
  'N_83': 6.0,
  'N_84': 6.0,
  'N_85': 6.0,
  'N_86': 6.0,
  'N_87': 6.0,
  'N_88': 6.0,
  'N_89': 6.0,
  'N_90': 6.0,
  'N_91': 6.0,
  'N_92': 6.0,
  'N_93': 6.0,
  'N_94': 6.0,
  'N_95': 6.0,
  'N_96': 6.0,
  'N_97': 6.0,
  'N_98': 6.0,
  'N_99': 6.0,
  'N_100': 6.0,
  'N_101': 6.0,
  'N_102': 6.0,
  'N_103': 6.0,
  'N_104': 6.0,
  'N_105': 6.0,
  'N_106': 6.0,
  'N_107': 6.0,
  'N_108': 6.0,
  'N_109': 6.0,
  'N_110': 6.0,
  'N_111': 6.0,
  'N_112': 6.0,
  'N_113': 6.0,
  'N_114': 6.0,
  'N_115': 6.0,
  'N_116': 6.0,
  'N_117': 6.0,
  'N_118': 6.0,
  'N_119': 6.0,
  'N_120': 6.0,
  'N_121': 6.0,
  'N_122': 6.0,
  'N_123': 6.0,
  'N_124': 6.0,
  'N_125': 6.0,
  'N_126': 6.0,
  'N_127': 6.0,
  'N_128': 7.0,
  'N_129': 7.0,
  'N_130': 7.0,
  'N_131': 7.0,
  'N_132': 7.0,
  'N_133': 7.0,
  'N_134': 7.0,
  'N_135': 7.0,
  'N_136': 7.0,
  'N_137': 7.0,
  'N_138': 7.0,
  'N_139': 7.0,
  'N_140': 7.0,
  'N_141': 7.0,
  'N_142': 7.0,
  'N_143': 7.0,
  'N_144': 7.0,
  'N_145': 7.0,
  'N_146': 7.0,
  'N_147': 7.0,
  'N_148': 7.0,
  'N_149': 7.0,
  'N_150': 7.0,
  'N_151': 7.0,
  'N_152': 7.0,
  'N_154': 7.0,
  'N_155': 7.0,
  'N_156': 7.0,
  'N_157': 7.0,
  'N_158': 7.0,
  'N_159': 7.0,
  'N_160': 7.0,
  'N_161': 7.0,
  'N_162': 7.0,
  'N_163': 7.0,
  'N_164': 7.0,
  'N_165': 7.0,
  'N_166': 7.0,
  'N_167': 7.0,
  'N_168': 7.0,
  'N_169': 7.0,
  'N_170': 7.0,
  'N_171': 7.0,
  'N_172': 7.0,
  'N_173': 7.0,
  'N_174': 7.0,
  'N_175': 7.0,
  'N_176': 7.0,
  'N_177': 7.0,
  'N_178': 7.0,
  'N_179': 7.0,
  'N_180': 7.0,
  'N_181': 7.0,
  'N_182': 7.0,
  'N_183': 7.0,
  'N_184': 7.0,
  'N_185': 7.0,
  'N_186': 7.0,
  'N_187': 7.0,
  'N_188': 7.0,
  'N_189': 7.0,
  'N_190': 7.0,
  'N_191': 7.0,
  'N_192': 7.0,
  'N_193': 7.0,
  'N_194': 7.0,
  'N_195': 7.0,
  'N_196': 7.0,
  'N_197': 7.0,
  'N_198': 7.0,
  'N_199': 7.0,
  'N_200': 7.0,
  'N_201': 7.0,
  'N_202': 7.0,
  'N_203': 7.0,
  'N_204': 7.0,
  'N_205': 7.0,
  'N_206': 7.0,
  'N_207': 7.0,
  'N_208': 7.0,
  'N_209': 7.0,
  'N_210': 7.0,
  'N_211': 7.0,
  'N_212': 7.0,
  'N_213': 7.0,
  'N_214': 7.0,
  'N_215': 7.0,
  'N_216': 7.0,
  'N_217': 7.0,
  'N_218': 7.0,
  'N_219': 7.0,
  'N_220': 7.0,
  'N_221': 7.0,
  'N_222': 7.0,
  'N_223': 7.0,
  'N_224': 7.0,
  'N_225': 7.0,
  'N_226': 7.0,
  'N_227': 7.0,
  'N_228': 7.0,
  'N_229': 7.0,
  'N_230': 7.0,
  'N_231': 7.0,
  'N_232': 7.0,
  'N_233': 7.0,
  'N_234': 7.0,
  'N_235': 7.0,
  'N_236': 7.0,
  'N_237': 7.0,
  'N_238': 7.0,
  'N_239': 7.0,
  'N_240': 7.0,
  'N_241': 7.0,
  'N_242': 7.0,
  'N_243': 7.0,
  'N_245': 7.0,
  'N_246': 7.0,
  'N_247': 7.0,
  'N_248': 7.0,
  'N_249': 7.0,
  'N_250': 7.0,
  'N_251': 7.0,
  'N_252': 7.0,
  'N_253': 7.0,
  'N_254': 7.0,
  'N_255': 7.0,
  'N_256': 8.0,
  'N_257': 8.0,
  'N_258': 8.0,
  'N_259': 8.0,
  'N_260': 8.0,
  'N_261': 8.0,
  'N_262': 8.0,
  'N_263': 8.0,
  'N_264': 8.0,
  'N_265': 8.0,
  'N_266': 8.0,
  'N_267': 8.0,
  'N_268': 8.0,
  'N_269': 8.0,
  'N_270': 8.0,
  'N_271': 8.0,
  'N_274': 8.0,
  'N_275': 8.0,
  'N_276': 8.0,
  'N_277': 8.0,
  'N_278': 8.0,
  'N_279': 8.0,
  'N_280': 8.0,
  'N_281': 8.0,
  'N_282': 8.0,
  'N_283': 8.0,
  'N_284': 8.0,
  'N_285': 8.0,
  'N_286': 8.0,
  'N_287': 8.0,
  'N_288': 8.0,
  'N_289': 8.0,
  'N_290': 8.0,
  'N_291': 8.0,
  'N_292': 8.0,
  'N_293': 8.0,
  'N_294': 8.0,
  'N_295': 8.0,
  'N_296': 8.0,
  'N_297': 8.0,
  'N_298': 8.0,
  'N_299': 8.0,
  'N_300': 8.0,
  'N_301': 8.0,
  'N_302': 8.0,
  'N_303': 8.0,
  'N_304': 8.0,
  'N_305': 8.0,
  'N_306': 8.0,
  'N_307': 8.0,
  'N_308': 8.0,
  'N_309': 8.0,
  'N_310': 8.0,
  'N_311': 8.0,
  'N_312': 8.0,
  'N_313': 8.0,
  'N_314': 8.0,
  'N_315': 8.0,
  'N_316': 8.0,
  'N_317': 8.0,
  'N_318': 8.0,
  'N_319': 8.0,
  'N_320': 8.0,
  'N_321': 8.0,
  'N_322': 8.0,
  'N_323': 8.0,
  'N_324': 8.0,
  'N_325': 8.0,
  'N_326': 8.0,
  'N_327': 8.0,
  'N_328': 8.0,
  'N_329': 8.0,
  'N_330': 8.0,
  'N_331': 8.0,
  'N_332': 8.0,
  'N_333': 8.0,
  'N_334': 8.0,
  'N_335': 8.0,
  'N_336': 8.0,
  'N_337': 8.0,
  'N_338': 8.0,
  'N_339': 8.0,
  'N_340': 8.0,
  'N_341': 8.0,
  'N_342': 8.0,
  'N_343': 8.0,
  'N_344': 8.0,
  'N_345': 8.0,
  'N_346': 8.0,
  'N_347': 8.0,
  'N_348': 8.0,
  'N_349': 8.0,
  'N_350': 8.0,
  'N_351': 8.0,
  'N_353': 8.0,
  'N_354': 8.0,
  'N_355': 8.0,
  'N_356': 8.0,
  'N_357': 8.0,
  'N_359': 8.0,
  'N_360': 8.0,
  'N_361': 8.0,
  'N_362': 8.0,
  'N_363': 8.0,
  'N_365': 8.0,
  'N_366': 8.0,
  'N_367': 8.0,
  'N_368': 8.0,
  'N_369': 8.0,
  'N_370': 8.0,
  'N_371': 8.0,
  'N_372': 8.0,
  'N_373': 8.0,
  'N_374': 8.0,
  'N_375': 8.0,
  'N_376': 8.0,
  'N_377': 8.0,
  'N_378': 8.0,
  'N_379': 8.0,
  'N_380': 8.0,
  'N_381': 8.0,
  'N_382': 8.0,
  'N_383': 8.0,
  'N_384': 8.0,
  'N_385': 8.0,
  'N_386': 8.0,
  'N_387': 8.0,
  'N_388': 8.0,
  'N_389': 8.0,
  'N_390': 8.0,
  'N_391': 8.0,
  'N_392': 8.0,
  'N_393': 8.0,
  'N_394': 8.0,
  'N_395': 8.0,
  'N_396': 8.0,
  'N_397': 8.0,
  'N_398': 8.0,
  'N_399': 8.0,
  'N_400': 8.0,
  'N_401': 8.0,
  'N_402': 8.0,
  'N_403': 8.0,
  'N_404': 8.0,
  'N_405': 8.0,
  'N_406': 8.0,
  'N_407': 8.0,
  'N_408': 8.0,
  'N_409': 8.0,
  'N_410': 8.0,
  'N_411': 8.0,
  'N_413': 8.0,
  'N_415': 8.0,
  'N_416': 8.0,
  'N_417': 8.0,
  'N_418': 8.0,
  'N_419': 8.0,
  'N_420': 8.0,
  'N_421': 8.0,
  'N_422': 8.0,
  'N_423': 8.0,
  'N_424': 8.0,
  'N_425': 8.0,
  'N_426': 8.0,
  'N_427': 8.0,
  'N_428': 8.0,
  'N_429': 8.0,
  'N_430': 8.0,
  'N_431': 8.0,
  'N_432': 8.0,
  'N_433': 8.0,
  'N_434': 8.0,
  'N_435': 8.0,
  'N_436': 8.0,
  'N_437': 8.0,
  'N_438': 8.0,
  'N_439': 8.0,
  'N_440': 8.0,
  'N_441': 8.0,
  'N_442': 8.0,
  'N_443': 8.0,
  'N_444': 8.0,
  'N_445': 8.0,
  'N_446': 8.0,
  'N_447': 8.0,
  'N_449': 8.0,
  'N_450': 8.0,
  'N_451': 8.0,
  'N_452': 8.0,
  'N_453': 8.0,
  'N_455': 8.0,
  'N_456': 8.0,
  'N_457': 8.0,
  'N_458': 8.0,
  'N_460': 8.0,
  'N_461': 8.0,
  'N_463': 8.0,
  'N_464': 8.0,
  'N_465': 8.0,
  'N_466': 8.0,
  'N_467': 8.0,
  'N_468': 8.0,
  'N_469': 8.0,
  'N_470': 8.0,
  'N_471': 8.0,
  'N_472': 8.0,
  'N_473': 8.0,
  'N_474': 8.0,
  'N_475': 8.0,
  'N_476': 8.0,
  'N_477': 8.0,
  'N_478': 8.0,
  'N_479': 8.0,
  'N_480': 8.0,
  'N_481': 8.0,
  'N_482': 8.0,
  'N_483': 8.0,
  'N_484': 8.0,
  'N_485': 8.0,
  'N_487': 8.0,
  'N_488': 8.0,
  'N_489': 8.0,
  'N_491': 8.0,
  'N_492': 8.0,
  'N_493': 8.0,
  'N_495': 8.0,
  'N_496': 8.0,
  'N_497': 8.0,
  'N_498': 8.0,
  'N_499': 8.0,
  'N_501': 8.0,
  'N_502': 8.0,
  'N_503': 8.0,
  'N_504': 8.0,
  'N_505': 8.0,
  'N_506': 8.0,
  'N_507': 8.0,
  'N_508': 9.0,
  'N_509': 9.0,
  'N_510': 9.0,
  'N_511': 9.0,
  'N_512': 9.0,
  'N_513': 9.0,
  'N_514': 9.0,
  'N_515': 9.0,
  'N_516': 9.0,
  'N_517': 9.0,
  'N_518': 9.0,
  'N_519': 9.0,
  'N_520': 9.0,
  'N_521': 9.0,
  'N_522': 9.0,
  'N_523': 9.0,
  'N_524': 9.0,
  'N_525': 9.0,
  'N_526': 9.0,
  'N_527': 9.0,
  'N_528': 9.0,
  'N_529': 9.0,
  'N_530': 9.0,
  'N_531': 9.0,
  'N_532': 9.0,
  'N_533': 9.0,
  'N_534': 9.0,
  'N_535': 9.0,
  'N_536': 9.0,
  'N_537': 9.0,
  'N_538': 9.0,
  'N_539': 9.0,
  'N_540': 9.0,
  'N_541': 9.0,
  'N_542': 9.0,
  'N_543': 9.0,
  'N_544': 9.0,
  'N_545': 9.0,
  'N_546': 9.0,
  'N_547': 9.0,
  'N_548': 9.0,
  'N_549': 9.0,
  'N_550': 9.0,
  'N_551': 9.0,
  'N_552': 9.0,
  'N_553': 9.0,
  'N_554': 9.0,
  'N_555': 9.0,
  'N_556': 9.0,
  'N_557': 9.0,
  'N_558': 9.0,
  'N_559': 9.0,
  'N_560': 9.0,
  'N_561': 9.0,
  'N_562': 9.0,
  'N_563': 9.0,
  'N_564': 9.0,
  'N_565': 9.0,
  'N_566': 9.0,
  'N_567': 9.0,
  'N_568': 9.0,
  'N_570': 9.0,
  'N_571': 9.0,
  'N_572': 9.0,
  'N_573': 9.0,
  'N_574': 9.0,
  'N_575': 9.0,
  'N_576': 9.0,
  'N_577': 9.0,
  'N_578': 9.0,
  'N_579': 9.0,
  'N_580': 9.0,
  'N_581': 9.0,
  'N_582': 9.0,
  'N_583': 9.0,
  'N_584': 9.0,
  'N_585': 9.0,
  'N_586': 9.0,
  'N_587': 9.0,
  'N_588': 9.0,
  'N_589': 9.0,
  'N_590': 9.0,
  'N_591': 9.0,
  'N_592': 9.0,
  'N_593': 9.0,
  'N_594': 9.0,
  'N_595': 9.0,
  'N_596': 9.0,
  'N_597': 9.0,
  'N_598': 9.0,
  'N_599': 9.0,
  'N_601': 9.0,
  'N_602': 9.0,
  'N_603': 9.0,
  'N_604': 9.0,
  'N_605': 9.0,
  'N_607': 9.0,
  'N_608': 9.0,
  'N_609': 9.0,
  'N_610': 9.0,
  'N_611': 9.0,
  'N_612': 9.0,
  'N_614': 9.0,
  'N_615': 9.0,
  'N_616': 9.0,
  'N_617': 9.0,
  'N_619': 9.0,
  'N_620': 9.0,
  'N_621': 9.0,
  'N_622': 9.0,
  'N_623': 9.0,
  'N_624': 9.0,
  'N_625': 9.0,
  'N_627': 9.0,
  'N_628': 9.0,
  'N_629': 9.0,
  'N_630': 9.0,
  'N_631': 9.0,
  'N_632': 9.0,
  'N_633': 9.0,
  'N_634': 9.0,
  'N_635': 9.0,
  'N_636': 9.0,
  'N_637': 9.0,
  'N_638': 9.0,
  'N_639': 9.0,
  'N_640': 9.0,
  'N_641': 9.0,
  'N_642': 9.0,
  'N_643': 9.0,
  'N_644': 9.0,
  'N_646': 9.0,
  'N_647': 9.0,
  'N_648': 9.0,
  'N_649': 9.0,
  'N_650': 9.0,
  'N_651': 9.0,
  'N_652': 9.0,
  'N_653': 9.0,
  'N_654': 9.0,
  'N_656': 9.0,
  'N_657': 9.0,
  'N_658': 9.0,
  'N_659': 9.0,
  'N_660': 9.0,
  'N_661': 9.0,
  'N_662': 9.0,
  'N_663': 9.0,
  'N_666': 9.0,
  'N_667': 9.0,
  'N_668': 9.0,
  'N_669': 9.0,
  'N_670': 9.0,
  'N_671': 9.0,
  'N_673': 9.0,
  'N_674': 9.0,
  'N_675': 9.0,
  'N_676': 9.0,
  'N_677': 9.0,
  'N_678': 9.0,
  'N_679': 9.0,
  'N_680': 9.0,
  'N_681': 9.0,
  'N_682': 9.0,
  'N_683': 9.0,
  'N_684': 9.0,
  'N_685': 9.0,
  'N_687': 9.0,
  'N_688': 9.0,
  'N_689': 9.0,
  'N_690': 9.0,
  'N_691': 9.0,
  'N_692': 9.0,
  'N_693': 9.0,
  'N_694': 9.0,
  'N_695': 9.0,
  'N_696': 9.0,
  'N_697': 9.0,
  'N_700': 9.0,
  'N_702': 9.0,
  'N_703': 9.0,
  'N_704': 9.0,
  'N_705': 9.0,
  'N_706': 9.0,
  'N_707': 9.0,
  'N_708': 9.0,
  'N_709': 9.0,
  'N_712': 9.0,
  'N_713': 9.0,
  'N_714': 9.0,
  'N_715': 9.0,
  'N_718': 9.0,
  'N_719': 9.0,
  'N_720': 9.0,
  'N_721': 9.0,
  'N_722': 9.0,
  'N_723': 9.0,
  'N_724': 9.0,
  'N_725': 9.0,
  'N_726': 9.0,
  'N_727': 9.0,
  'N_728': 9.0,
  'N_729': 9.0,
  'N_730': 9.0,
  'N_731': 9.0,
  'N_732': 9.0,
  'N_733': 9.0,
  'N_734': 9.0,
  'N_735': 9.0,
  'N_737': 9.0,
  'N_738': 9.0,
  'N_739': 9.0,
  'N_740': 9.0,
  'N_741': 9.0,
  'N_742': 9.0,
  'N_743': 9.0,
  'N_744': 9.0,
  'N_745': 9.0,
  'N_746': 9.0,
  'N_747': 9.0,
  'N_748': 9.0,
  'N_749': 9.0,
  'N_750': 9.0,
  'N_751': 9.0,
  'N_752': 9.0,
  'N_753': 9.0,
  'N_754': 9.0,
  'N_755': 9.0,
  'N_756': 9.0,
  'N_757': 9.0,
  'N_758': 9.0,
  'N_759': 9.0,
  'N_760': 9.0,
  'N_761': 9.0,
  'N_762': 9.0,
  'N_763': 9.0,
  'N_764': 9.0,
  'N_765': 9.0,
  'N_766': 9.0,
  'N_768': 9.0,
  'N_769': 9.0,
  'N_770': 9.0,
  'N_771': 9.0,
  'N_772': 9.0,
  'N_773': 9.0,
  'N_774': 9.0,
  'N_775': 9.0,
  'N_776': 9.0,
  'N_777': 9.0,
  'N_778': 9.0,
  'N_779': 9.0,
  'N_780': 9.0,
  'N_781': 9.0,
  'N_782': 9.0,
  'N_783': 9.0,
  'N_785': 9.0,
  'N_786': 9.0,
  'N_787': 9.0,
  'N_788': 9.0,
  'N_789': 9.0,
  'N_790': 9.0,
  'N_792': 9.0,
  'N_793': 9.0,
  'N_794': 9.0,
  'N_795': 9.0,
  'N_796': 9.0,
  'N_797': 9.0,
  'N_798': 9.0,
  'N_799': 9.0,
  'N_800': 9.0,
  'N_801': 9.0,
  'N_802': 9.0,
  'N_803': 9.0,
  'N_804': 9.0,
  'N_805': 9.0,
  'N_806': 9.0,
  'N_807': 9.0,
  'N_808': 9.0,
  'N_809': 9.0,
  'N_810': 9.0,
  'N_814': 9.0,
  'N_815': 9.0,
  'N_816': 9.0,
  'N_817': 9.0,
  'N_818': 9.0,
  'N_819': 9.0,
  'N_820': 9.0,
  'N_821': 9.0,
  'N_822': 9.0,
  'N_823': 9.0,
  'N_824': 9.0,
  'N_825': 9.0,
  'N_826': 9.0,
  'N_827': 9.0,
  'N_828': 9.0,
  'N_829': 9.0,
  'N_830': 9.0,
  'N_831': 9.0,
  'N_832': 9.0,
  'N_833': 9.0,
  'N_834': 9.0,
  'N_835': 9.0,
  'N_836': 9.0,
  'N_837': 9.0,
  'N_838': 9.0,
  'N_839': 9.0,
  'N_840': 9.0,
  'N_841': 9.0,
  'N_842': 9.0,
  'N_843': 9.0,
  'N_845': 9.0,
  'N_846': 9.0,
  'N_847': 9.0,
  'N_848': 9.0,
  'N_849': 9.0,
  'N_850': 9.0,
  'N_851': 9.0,
  'N_852': 9.0,
  'N_853': 9.0,
  'N_854': 9.0,
  'N_855': 9.0,
  'N_856': 9.0,
  'N_857': 9.0,
  'N_858': 9.0,
  'N_859': 9.0,
  'N_860': 9.0,
  'N_861': 9.0,
  'N_862': 9.0,
  'N_863': 9.0,
  'N_864': 9.0,
  'N_865': 9.0,
  'N_866': 9.0,
  'N_867': 9.0,
  'N_868': 9.0,
  'N_869': 9.0,
  'N_870': 9.0,
  'N_871': 9.0,
  'N_872': 9.0,
  'N_873': 9.0,
  'N_875': 9.0,
  'N_876': 9.0,
  'N_877': 9.0,
  'N_878': 9.0,
  'N_879': 9.0,
  'N_880': 9.0,
  'N_881': 9.0,
  'N_882': 9.0,
  'N_883': 9.0,
  'N_884': 9.0,
  'N_885': 9.0,
  'N_886': 9.0,
  'N_887': 9.0,
  'N_888': 9.0,
  'N_890': 9.0,
  'N_891': 9.0,
  'N_892': 9.0,
  'N_893': 9.0,
  'N_894': 9.0,
  'N_895': 9.0,
  'N_896': 9.0,
  'N_897': 9.0,
  'N_898': 9.0,
  'N_900': 9.0,
  'N_902': 9.0,
  'N_903': 9.0,
  'N_904': 9.0,
  'N_905': 9.0,
  'N_906': 9.0,
  'N_907': 9.0,
  'N_908': 9.0,
  'N_909': 9.0,
  'N_910': 9.0,
  'N_911': 9.0,
  'N_913': 9.0,
  'N_914': 9.0,
  'N_915': 9.0,
  'N_916': 9.0,
  'N_917': 9.0,
  'N_918': 9.0,
  'N_919': 9.0,
  'N_920': 9.0,
  'N_921': 9.0,
  'N_922': 9.0,
  'N_924': 9.0,
  'N_925': 9.0,
  'N_926': 9.0,
  'N_927': 9.0,
  'N_928': 9.0,
  'N_929': 9.0,
  'N_931': 9.0,
  'N_934': 9.0,
  'N_935': 9.0,
  'N_936': 9.0,
  'N_937': 9.0,
  'N_938': 9.0,
  'N_939': 9.0,
  'N_940': 9.0,
  'N_941': 9.0,
  'N_942': 9.0,
  'N_943': 9.0,
  'N_944': 9.0,
  'N_945': 9.0,
  'N_949': 9.0,
  'N_950': 9.0,
  'N_952': 9.0,
  'N_954': 9.0,
  'N_955': 9.0,
  'N_959': 9.0,
  'N_960': 9.0,
  'N_961': 9.0,
  'N_962': 9.0,
  'N_963': 9.0,
  'N_964': 9.0,
  'N_965': 9.0,
  'N_966': 9.0,
  'N_967': 9.0,
  'N_970': 9.0,
  'N_971': 9.0,
  'N_973': 9.0,
  'N_974': 9.0,
  'N_975': 9.0,
  'N_976': 9.0,
  'N_977': 9.0,
  'N_978': 9.0,
  'N_979': 9.0,
  'N_980': 9.0,
  'N_981': 9.0,
  'N_982': 10.0,
  'N_983': 10.0,
  'N_984': 10.0,
  'N_985': 10.0,
  'N_986': 10.0,
  'N_987': 10.0,
  'N_988': 10.0,
  'N_989': 10.0,
  'N_990': 10.0,
  'N_991': 10.0,
  'N_992': 10.0,
  'N_993': 10.0,
  'N_995': 10.0,
  'N_996': 10.0,
  'N_997': 10.0,
  'N_998': 10.0,
  'N_999': 10.0,
  'N_1000': 10.0,
  'N_1001': 10.0,
  'N_1002': 10.0,
  'N_1003': 10.0,
  'N_1004': 10.0,
  'N_1005': 10.0,
  'N_1006': 10.0,
  'N_1007': 10.0,
  'N_1008': 10.0,
  'N_1009': 10.0,
  'N_1010': 10.0,
  'N_1011': 10.0,
  'N_1012': 10.0,
  'N_1013': 10.0,
  'N_1014': 10.0,
  'N_1015': 10.0,
  'N_1016': 10.0,
  'N_1017': 10.0,
  'N_1018': 10.0,
  'N_1019': 10.0,
  'N_1020': 10.0,
  'N_1021': 10.0,
  'N_1022': 10.0,
  'N_1023': 10.0,
  'N_1024': 10.0,
  'N_1025': 10.0,
  'N_1026': 10.0,
  'N_1027': 10.0,
  'N_1028': 10.0,
  'N_1029': 10.0,
  'N_1030': 10.0,
  'N_1031': 10.0,
  'N_1032': 10.0,
  'N_1033': 10.0,
  'N_1034': 10.0,
  'N_1036': 10.0,
  'N_1037': 10.0,
  'N_1038': 10.0,
  'N_1039': 10.0,
  'N_1041': 10.0,
  'N_1042': 10.0,
  'N_1043': 10.0,
  'N_1046': 10.0,
  'N_1047': 10.0,
  'N_1048': 10.0,
  'N_1049': 10.0,
  'N_1050': 10.0,
  'N_1052': 10.0,
  'N_1054': 10.0,
  'N_1055': 10.0,
  'N_1056': 10.0,
  'N_1057': 10.0,
  'N_1058': 10.0,
  'N_1059': 10.0,
  'N_1060': 10.0,
  'N_1061': 10.0,
  'N_1062': 10.0,
  'N_1063': 10.0,
  'N_1064': 10.0,
  'N_1065': 10.0,
  'N_1066': 10.0,
  'N_1067': 10.0,
  'N_1068': 10.0,
  'N_1069': 10.0,
  'N_1070': 10.0,
  'N_1071': 10.0,
  ...},
 'Ds': {'N_1': 34.0,
  'N_2': 33.0,
  'N_3': 30.0,
  'N_4': 32.0,
  'N_5': 28.0,
  'N_6': 27.0,
  'N_7': 29.0,
  'N_8': 31.0,
  'N_9': 25.0,
  'N_10': 25.0,
  'N_11': 27.0,
  'N_12': 26.0,
  'N_13': 26.0,
  'N_14': 28.0,
  'N_15': 24.0,
  'N_16': 29.0,
  'N_17': 30.0,
  'N_18': 23.0,
  'N_19': 24.0,
  'N_20': 24.0,
  'N_21': 20.0,
  'N_22': 18.0,
  'N_23': 26.0,
  'N_24': 25.0,
  'N_25': 21.0,
  'N_26': 25.0,
  'N_27': 22.0,
  'N_28': 23.0,
  'N_29': 27.0,
  'N_30': 23.0,
  'N_31': 21.0,
  'N_32': 28.0,
  'N_33': 26.0,
  'N_34': 27.0,
  'N_35': 29.0,
  'N_36': 22.0,
  'N_37': 22.0,
  'N_38': 23.0,
  'N_39': 15.0,
  'N_40': 20.0,
  'N_41': 23.0,
  'N_42': 17.0,
  'N_43': 19.0,
  'N_44': 17.0,
  'N_45': 17.0,
  'N_46': 25.0,
  'N_47': 19.0,
  'N_48': 24.0,
  'N_49': 17.0,
  'N_50': 13.0,
  'N_51': 20.0,
  'N_52': 19.0,
  'N_53': 24.0,
  'N_54': 21.0,
  'N_55': 15.0,
  'N_56': 22.0,
  'N_57': 11.0,
  'N_58': 25.0,
  'N_59': 26.0,
  'N_60': 22.0,
  'N_61': 8.0,
  'N_62': 15.0,
  'N_63': 20.0,
  'N_64': 27.0,
  'N_65': 27.0,
  'N_66': 25.0,
  'N_67': 17.0,
  'N_68': 17.0,
  'N_69': 26.0,
  'N_70': 27.0,
  'N_71': 28.0,
  'N_72': 21.0,
  'N_73': 20.0,
  'N_74': 21.0,
  'N_75': 15.0,
  'N_76': 12.0,
  'N_77': 22.0,
  'N_78': 13.0,
  'N_79': 14.0,
  'N_80': 17.0,
  'N_81': 19.0,
  'N_82': 22.0,
  'N_83': 19.0,
  'N_84': 14.0,
  'N_85': 16.0,
  'N_86': 18.0,
  'N_87': 16.0,
  'N_88': 11.0,
  'N_89': 16.0,
  'N_90': 10.0,
  'N_91': 16.0,
  'N_92': 23.0,
  'N_93': 24.0,
  'N_94': 10.0,
  'N_95': 18.0,
  'N_96': 20.0,
  'N_97': 23.0,
  'N_98': 16.0,
  'N_99': 13.0,
  'N_100': 9.0,
  'N_101': 12.0,
  'N_102': 19.0,
  'N_103': 6.0,
  'N_104': 18.0,
  'N_105': 17.0,
  'N_106': 22.0,
  'N_107': 23.0,
  'N_108': 16.0,
  'N_109': 20.0,
  'N_110': 14.0,
  'N_111': 14.0,
  'N_112': 13.0,
  'N_113': 21.0,
  'N_114': 10.0,
  'N_115': 6.0,
  'N_116': 18.0,
  'N_117': 24.0,
  'N_118': 25.0,
  'N_119': 19.0,
  'N_120': 15.0,
  'N_121': 21.0,
  'N_122': 3.0,
  'N_123': 7.0,
  'N_124': 11.0,
  'N_125': 14.0,
  'N_126': 6.0,
  'N_127': 19.0,
  'N_128': 19.0,
  'N_129': 26.0,
  'N_130': 26.0,
  'N_131': 26.0,
  'N_132': 16.0,
  'N_133': 24.0,
  'N_134': 16.0,
  'N_135': 15.0,
  'N_136': 1.0,
  'N_137': 16.0,
  'N_138': 25.0,
  'N_139': 15.0,
  'N_140': 22.0,
  'N_141': 26.0,
  'N_142': 27.0,
  'N_143': 24.0,
  'N_144': 18.0,
  'N_145': 20.0,
  'N_146': 11.0,
  'N_147': 19.0,
  'N_148': 19.0,
  'N_149': 20.0,
  'N_150': 9.0,
  'N_151': 14.0,
  'N_152': 11.0,
  'N_154': 7.0,
  'N_155': 21.0,
  'N_156': 9.0,
  'N_157': 12.0,
  'N_158': 13.0,
  'N_159': 10.0,
  'N_160': 14.0,
  'N_161': 16.0,
  'N_162': 9.0,
  'N_163': 18.0,
  'N_164': 18.0,
  'N_165': 21.0,
  'N_166': 12.0,
  'N_167': 18.0,
  'N_168': 13.0,
  'N_169': 13.0,
  'N_170': 11.0,
  'N_171': 15.0,
  'N_172': 3.0,
  'N_173': 17.0,
  'N_174': 8.0,
  'N_175': 15.0,
  'N_176': 10.0,
  'N_177': 9.0,
  'N_178': 3.0,
  'N_179': 15.0,
  'N_180': 8.0,
  'N_181': 9.0,
  'N_182': 15.0,
  'N_183': 2.0,
  'N_184': 19.0,
  'N_185': 22.0,
  'N_186': 23.0,
  'N_187': 22.0,
  'N_188': 5.0,
  'N_189': 9.0,
  'N_190': 10.0,
  'N_191': 17.0,
  'N_192': 14.0,
  'N_193': 19.0,
  'N_194': 19.0,
  'N_195': 22.0,
  'N_196': 8.0,
  'N_197': 15.0,
  'N_198': 12.0,
  'N_199': 8.0,
  'N_200': 8.0,
  'N_201': 5.0,
  'N_202': 11.0,
  'N_203': 10.0,
  'N_204': 8.0,
  'N_205': 18.0,
  'N_206': 5.0,
  'N_207': 3.0,
  'N_208': 2.0,
  'N_209': 17.0,
  'N_210': 16.0,
  'N_211': 12.0,
  'N_212': 21.0,
  'N_213': 21.0,
  'N_214': 22.0,
  'N_215': 18.0,
  'N_216': 15.0,
  'N_217': 9.0,
  'N_218': 19.0,
  'N_219': 11.0,
  'N_220': 13.0,
  'N_221': 8.0,
  'N_222': 12.0,
  'N_223': 13.0,
  'N_224': 12.0,
  'N_225': 5.0,
  'N_226': 20.0,
  'N_227': 16.0,
  'N_228': 5.0,
  'N_229': 9.0,
  'N_230': 5.0,
  'N_231': 4.0,
  'N_232': 5.0,
  'N_233': 17.0,
  'N_234': 19.0,
  'N_235': 23.0,
  'N_236': 24.0,
  'N_237': 14.0,
  'N_238': 9.0,
  'N_239': 18.0,
  'N_240': 5.0,
  'N_241': 14.0,

In [11]:
## generate tree infos with cell state
for e_n in phase_tree_2.traverse("preorder"):
    if e_n.is_root():
        e_n.add_features(state = "A")
    else:
        if not e_n.is_leaf():
            #use_mheight = subtree_depth_infos_2["height"][e_n.name]
            use_mheight = subtree_depth_infos_2["depth"][e_n.name]
        else:
            #use_mheight = subtree_depth_infos_2["height"][e_n.up.name]
            use_mheight = subtree_depth_infos_2["depth"][e_n.up.name]
        if use_mheight > 0.7:
            use_transmx = phase_1_transmx
        else:
            use_transmx = phase_2_transmx
        use_states = use_transmx.columns.to_list()
        ancestor_n_state = e_n.up.state
        #print(e_n.up.state)
        #print(use_transmx)
        e_n.add_features(state = choices(use_states, weights=use_transmx.loc[ancestor_n_state])[0])

In [17]:
from collections import defaultdict

## =========== define functions ==============
def write_results(tree_obj, node_infos_path, name = False):
    ## add name to tree
    node_state_infos = defaultdict(list)
    i = 1
    for each_node in tree_obj.traverse():
        if not name:
            each_node.name = "N_" + str(i)
        each_node.dist = 1
        i += 1
        ##
        node_state_infos["NodeName"].append(each_node.name)
        node_state_infos["state"].append(each_node.state)
        node_state_infos["is_leaf"].append(each_node.is_leaf())
        node_state_infos["is_root"].append(each_node.is_root())
    tree_info_df = pd.DataFrame.from_dict(node_state_infos)
    ## write out results
    #tree_obj.write(outfile=tree_path, format = 1)
    tree_info_df.to_csv(node_infos_path, sep = '\t', index = False)

In [19]:
save_path = "/mnt/data5/disk/yangwj/Scripts/Fig2/new_two_phase_tree/"
write_results(tree_obj = phase_tree_2,
              node_infos_path = os.path.join(save_path, "new_two_phase_tree_50000_depth_nodeInfo.txt"),
              name = False)

In [15]:
## check state composition
check_state_infos = defaultdict(list)
j = 1
for each_n in phase_tree_2.traverse():
#     if each_n.name == "":
#         each_n.name = "N_" + str(j)
#     each_n.dist = 1
#     j += 1
    check_state_infos["NodeName"].append(each_n.name)
    check_state_infos["state"].append(each_n.state)
    check_state_infos["is_leaf"].append(each_n.is_leaf())
    check_state_infos["is_root"].append(each_n.is_root())
    #check_state_infos["state"].append(each_n.state)

In [17]:
len(check_state_infos['NodeName'])

99999

In [18]:
len(check_state_infos['state'])

99999

In [19]:
check_state_infos_df = pd.DataFrame.from_dict(check_state_infos)

In [20]:
check_state_infos_df

      NodeName state  is_leaf  is_root
0          N_1     A    False     True
1          N_2     B    False    False
2          N_3     A    False    False
3          N_4     B    False    False
4          N_5     C    False    False
...        ...   ...      ...      ...
99994  N_99995     F     True    False
99995  N_99996     A     True    False
99996  N_99997     A     True    False
99997  N_99998     A     True    False
99998  N_99999     A     True    False

[99999 rows x 4 columns]

In [21]:
leaf_state_infos_df = check_state_infos_df[check_state_infos_df['is_leaf'] == True]

In [22]:
leaf_state_infos_df['state'].value_counts()

B    13595
A     9221
F     6739
E     6620
H     6122
G     5841
D      945
C      917
Name: state, dtype: int64